# Generated by Django 4.1.3 on 2022-11-15 02:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharia_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shariaboard2',
            name='text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
